# SPDX-FileCopyrightText: 2025 Frans van Dorsselaer
#
# SPDX-License-Identifier: GPL-3.0-only

---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install tooling
        run: |
          sudo apt-get update
          sudo apt-get install gcc-aarch64-linux-gnu

      - name: Build libudev (x64)
        run: |
          cd libudev-zero
          make libudev.a
          mkdir x64
          cp libudev.a x64
          make clean

      - name: Build libudev (arm64)
        run: |
          cd libudev-zero
          CC=aarch64-linux-gnu-gcc make libudev.a
          mkdir arm64
          cp libudev.a arm64
          make clean
