# SPDX-FileCopyrightText: 2025 Frans van Dorsselaer
#
# SPDX-License-Identifier: GPL-3.0-only

---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install tooling
        run: |
          sudo apt-get update
          sudo apt-get install gcc-aarch64-linux-gnu

      - name: Patch sources
        run: |
          cd WSL2-Linux-Kernel
          patch -p1 < ../WSL2-Linux-Kernel.diff

      - name: Build libudev (x64)
        run: |
          cd libudev-zero
          make libudev.a
          mkdir -p x64
          cp libudev.a x64
          make clean

      - name: Build libudev (arm64)
        run: |
          cd libudev-zero
          make CC=aarch64-linux-gnu-gcc AR=aarch64-linux-gnu-ar libudev.a
          mkdir -p arm64
          cp libudev.a arm64
          make clean

      - name: Build usbip (x64)
        run: |
          cd WSL2-Linux-Kernel/tools/usb/usbip
          autoconf
          ./configure LDFLAGS=-L`realpath ../../../../libudev-zero/x64`
          make
          mkdir -p "${{ github.workspace }}/x64"
          cp src/usbip "${{ github.workspace }}/x64"
          make clean

      - name: Build usbip (arm64)
        run: |
          cd WSL2-Linux-Kernel/tools/usb/usbip
          autoconf
          ./configure --host=aarch64-linux-gnu LDFLAGS=-L`realpath ../../../../libudev-zero/arm64`
          make
          mkdir -p "${{ github.workspace }}/arm64"
          cp src/usbip "${{ github.workspace }}/arm64"
          make clean

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-binaries
          path: |
            x64/
            arm64/
